<?php
/**
 * BT_Diagnostic — single-page truth layer for "did my changes actually ship?"
 *
 * Runs FIVE layers of checks on the live site and reports each independently.
 * Built specifically because the v32/33/34 ship cycle produced no visible
 * change despite plugin-version bumps reporting current. We need to know,
 * objectively, where the disconnect is.
 *
 * Layer 1 — FILE: are the modified source files actually on disk?
 * Layer 2 — TEMPLATE: which template is rendering each known page?
 * Layer 3 — CSS LOAD: which stylesheets are enqueued + actual file contents on disk?
 * Layer 4 — CSS CASCADE: dequeue events that strip our stylesheets
 * Layer 5 — RENDER OUTPUT: actual HTML markup for known fragments
 *
 * Access:
 *   WP Admin → BlockTicker → Diagnostic (admin-only, manage_options capability)
 *   OR
 *   /?bt-diagnose=1 with ?bt-diag-key=<random-key-shown-in-admin>
 *
 * Output is self-contained HTML with copy-to-clipboard so admins can paste
 * the entire report back to engineering.
 *
 * @since v119.28.36
 * @package BlockTicker
 */

if ( ! defined( 'ABSPATH' ) ) exit;

class BT_Diagnostic {

    const NONCE_KEY = 'bt_diag_nonce';
    const DIAG_KEY_OPTION = 'bt_diag_access_key';

    public static function init() {
        // Admin-only menu page
        add_action( 'admin_menu', array( __CLASS__, 'register_admin_page' ), 30 );

        // URL-token access for support / engineering (read-only key in option,
        // rotates on demand from admin). Allows pasting a one-shot URL to a
        // collaborator to see the report without granting admin login.
        add_action( 'init', array( __CLASS__, 'maybe_render_url_token' ), 1 );
    }

    public static function register_admin_page() {
        add_submenu_page(
            'blockticker',
            'Diagnostic',
            'Diagnostic',
            'manage_options',
            'bt-diagnostic',
            array( __CLASS__, 'render_admin_page' )
        );
    }

    /**
     * Public-URL render — only fires when ?bt-diagnose=1 is in the URL AND
     * a valid bt-diag-key is provided. The key is regenerated by clicking
     * "Rotate access key" in the admin UI.
     */
    public static function maybe_render_url_token() {
        if ( empty( $_GET['bt-diagnose'] ) ) return;
        $provided = sanitize_text_field( wp_unslash( $_GET['bt-diag-key'] ?? '' ) );
        $stored = get_option( self::DIAG_KEY_OPTION, '' );
        if ( ! $stored || ! hash_equals( $stored, $provided ) ) return;

        // Authorized — render the diagnostic and exit.
        nocache_headers();
        header( 'Content-Type: text/html; charset=UTF-8' );
        echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>BlockTicker Diagnostic</title>';
        self::render_inline_css();
        echo '</head><body class="bt-diag-page">';
        echo '<div class="bt-diag-banner">URL-token diagnostic · admin authentication bypassed via key</div>';
        self::render_report();
        echo '</body></html>';
        exit;
    }

    public static function render_admin_page() {
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_die( 'Insufficient permissions.' );
        }

        // Handle key-rotation action
        if ( ! empty( $_POST['bt_diag_rotate'] ) && check_admin_referer( self::NONCE_KEY ) ) {
            $new_key = wp_generate_password( 32, false, false );
            update_option( self::DIAG_KEY_OPTION, $new_key, false );
            echo '<div class="notice notice-success"><p>Access key rotated.</p></div>';
        }

        $diag_key = get_option( self::DIAG_KEY_OPTION, '' );
        if ( empty( $diag_key ) ) {
            $diag_key = wp_generate_password( 32, false, false );
            update_option( self::DIAG_KEY_OPTION, $diag_key, false );
        }

        $url_token_url = add_query_arg(
            array( 'bt-diagnose' => '1', 'bt-diag-key' => $diag_key ),
            home_url( '/' )
        );

        ?>
        <div class="wrap">
            <h1>BlockTicker Diagnostic</h1>
            <p>Five layers of truth-checking for "did my changes actually ship?" Each layer reports independently — read top to bottom, the first layer that fails is where the disconnect is.</p>

            <details style="margin:16px 0;background:#fff;border:1px solid #dcdcde;padding:8px 12px">
                <summary style="cursor:pointer;font-weight:600">Share with engineering (URL-token access)</summary>
                <p style="margin-top:12px">Paste this URL to a collaborator and they can see the same diagnostic without admin login. Anyone with the URL has read-only access to the report — rotate the key to invalidate.</p>
                <p><code style="word-break:break-all;display:block;background:#f6f7f7;padding:8px;border:1px solid #dcdcde;font-size:11px"><?php echo esc_html( $url_token_url ); ?></code></p>
                <form method="post">
                    <?php wp_nonce_field( self::NONCE_KEY ); ?>
                    <button type="submit" name="bt_diag_rotate" value="1" class="button">Rotate access key (invalidates old URL)</button>
                </form>
            </details>

            <div style="background:#fff;border:1px solid #dcdcde;padding:0">
                <?php self::render_inline_css(); ?>
                <div class="bt-diag-page">
                    <?php self::render_report(); ?>
                </div>
            </div>
        </div>
        <?php
    }

    private static function render_inline_css() {
        echo '<style>
            .bt-diag-page { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 16px 24px; max-width: 1100px; }
            .bt-diag-banner { background: #fbbf24; color: #0a0b0d; padding: 8px 16px; font-weight: 600; font-size: 13px; }
            .bt-diag-page h2 { margin: 24px 0 8px; padding: 8px 12px; background: #1d2327; color: #fff; border-radius: 4px; font-size: 16px; }
            .bt-diag-page h3 { margin: 16px 0 6px; font-size: 14px; color: #1d2327; }
            .bt-diag-status { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 11px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; }
            .bt-diag-status--ok { background: #d1fae5; color: #065f46; }
            .bt-diag-status--fail { background: #fee2e2; color: #991b1b; }
            .bt-diag-status--warn { background: #fef3c7; color: #92400e; }
            .bt-diag-status--info { background: #dbeafe; color: #1e40af; }
            .bt-diag-page table { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 12px; }
            .bt-diag-page th, .bt-diag-page td { border: 1px solid #dcdcde; padding: 6px 10px; text-align: left; vertical-align: top; }
            .bt-diag-page th { background: #f6f7f7; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
            .bt-diag-page code { font-family: "SF Mono", Monaco, Consolas, monospace; font-size: 11px; background: #f6f7f7; padding: 1px 4px; border-radius: 2px; }
            .bt-diag-page pre { background: #1d2327; color: #d4d4d4; padding: 10px 14px; border-radius: 4px; overflow-x: auto; font-size: 11px; line-height: 1.5; max-height: 300px; }
            .bt-diag-page .layer-summary { padding: 12px 16px; margin: 4px 0 16px; border-radius: 4px; font-weight: 600; }
            .bt-diag-page .layer-summary--ok { background: #d1fae5; color: #065f46; border-left: 4px solid #10b981; }
            .bt-diag-page .layer-summary--fail { background: #fee2e2; color: #991b1b; border-left: 4px solid #ef4444; }
            .bt-diag-page .layer-summary--warn { background: #fef3c7; color: #92400e; border-left: 4px solid #f59e0b; }
            .bt-diag-page .copy-section { background: #f6f7f7; padding: 10px 14px; border: 1px dashed #94a3b8; margin: 12px 0; font-family: monospace; font-size: 11px; white-space: pre-wrap; word-break: break-all; }
        </style>';
    }

    /**
     * The actual report — five layers in order.
     */
    private static function render_report() {
        echo '<p style="font-size:12px;color:#646970">Generated ' . esc_html( gmdate( 'Y-m-d H:i:s' ) ) . ' UTC · Plugin version <code>' . esc_html( BT_VERSION ) . '</code> · WP <code>' . esc_html( get_bloginfo( 'version' ) ) . '</code></p>';

        // ─── LAYER 1: FILE ──────────────────────────────────────────────
        echo '<h2>Layer 1 — File: are v32/33/34 changes physically on disk?</h2>';
        $layer1 = self::layer_1_file_check();
        self::render_layer_summary( $layer1 );

        // ─── LAYER 2: TEMPLATE ──────────────────────────────────────────
        echo '<h2>Layer 2 — Template: which file renders each page?</h2>';
        $layer2 = self::layer_2_template_resolution();
        self::render_layer_summary( $layer2 );

        // ─── LAYER 3: CSS LOAD ──────────────────────────────────────────
        echo '<h2>Layer 3 — CSS load: are v33 stylesheet rules on disk + enqueued?</h2>';
        $layer3 = self::layer_3_css_load();
        self::render_layer_summary( $layer3 );

        // ─── LAYER 4: CSS CASCADE ───────────────────────────────────────
        echo '<h2>Layer 4 — CSS cascade: dequeue events / theme overrides</h2>';
        $layer4 = self::layer_4_cascade_check();
        self::render_layer_summary( $layer4 );

        // ─── LAYER 5: RENDER OUTPUT ─────────────────────────────────────
        echo '<h2>Layer 5 — Render output: actual HTML markup for known fragments</h2>';
        $layer5 = self::layer_5_render_check();
        self::render_layer_summary( $layer5 );

        // ─── FINAL SUMMARY ──────────────────────────────────────────────
        echo '<h2>Diagnosis</h2>';
        self::render_final_diagnosis( array( $layer1, $layer2, $layer3, $layer4, $layer5 ) );
    }

    private static function render_layer_summary( $layer ) {
        $cls = 'layer-summary--' . $layer['status'];
        echo '<div class="layer-summary ' . esc_attr( $cls ) . '">' . esc_html( $layer['summary'] ) . '</div>';
        if ( ! empty( $layer['html'] ) ) {
            echo $layer['html']; // already escaped by check methods
        }
    }

    /* ════════════════════════════════════════════════════════════════════
     *  LAYER 1 — FILE CHECK
     *  ════════════════════════════════════════════════════════════════════ */

    /**
     * Verify that specific markers from v32/33/34 are physically present in
     * source files on disk. If a marker is missing, the upload was incomplete
     * or partial — explains everything downstream.
     */
    private static function layer_1_file_check() {
        $markers = array(
            // v32 markers
            array(
                'release' => 'v32',
                'file'    => 'templates/clean/landing.php',
                'find'    => 'home_url( \'/desk-brief/\' )',
                'desc'    => 'Hero CTA repaired (was desk-brief.html 404)',
            ),
            array(
                'release' => 'v32',
                'file'    => 'templates/clean/landing.php',
                'find'    => '<main id="main-content"',
                'desc'    => '<main> landmark for skip-link',
            ),
            array(
                'release' => 'v32',
                'file'    => 'assets/css/bt-tokens.css',
                'find'    => '#7B8AA0',
                'desc'    => '--bt-text-5 contrast bump (WCAG AA)',
            ),
            array(
                'release' => 'v32',
                'file'    => 'includes/class-cron-health.php',
                'find'    => 'class BT_Cron_Health',
                'desc'    => 'BT_Cron_Health class file present',
            ),
            // v33 markers
            array(
                'release' => 'v33',
                'file'    => 'includes/class-widgets.php',
                'find'    => 'fxlm-cft-asset__name',
                'desc'    => 'Crypto-table grid markup (was nested div)',
            ),
            array(
                'release' => 'v33',
                'file'    => 'assets/css/bt-tokens.css',
                'find'    => '§13.1  Crypto table asset cell',
                'desc'    => 'Crypto-table grid CSS block',
            ),
            array(
                'release' => 'v33',
                'file'    => 'assets/css/bt-tokens.css',
                'find'    => '§13.3  Asset-page background cap',
                'desc'    => 'Asset-page background !important cap',
            ),
            array(
                'release' => 'v33',
                'file'    => 'includes/class-cwv.php',
                'find'    => 'set_static_asset_cache_headers',
                'desc'    => 'Cache-Control: immutable header method',
            ),
            // v34 markers
            array(
                'release' => 'v34',
                'file'    => 'includes/class-page-provisioner.php',
                'find'    => 'pricing_page_content',
                'desc'    => 'Pricing page content helper',
            ),
            array(
                'release' => 'v34',
                'file'    => 'includes/class-page-provisioner.php',
                'find'    => 'guard_unpublished_pricing',
                'desc'    => 'Pricing private-page 404 guard',
            ),
            // v35 markers
            array(
                'release' => 'v35',
                'file'    => 'uninstall.php',
                'find'    => 'BT_PURGE_DATA_ON_UNINSTALL',
                'desc'    => 'Preserve-by-default uninstall',
            ),
        );

        $rows = array();
        $fail_count = 0;
        $missing_files = array();

        foreach ( $markers as $m ) {
            $path = BT_DIR . $m['file'];
            $status = 'ok';
            $detail = '';

            if ( ! file_exists( $path ) ) {
                $status = 'fail';
                $detail = 'FILE MISSING';
                $fail_count++;
                $missing_files[] = $m['file'];
            } else {
                $contents = file_get_contents( $path );
                if ( strpos( $contents, $m['find'] ) === false ) {
                    $status = 'fail';
                    $detail = 'marker not in file';
                    $fail_count++;
                } else {
                    $detail = 'present';
                }
                $detail .= ' · ' . size_format( filesize( $path ) ) . ' · mtime ' . gmdate( 'Y-m-d H:i', filemtime( $path ) );
            }

            $rows[] = sprintf(
                '<tr><td>%s</td><td><code>%s</code></td><td>%s</td><td><code>%s</code></td><td><span class="bt-diag-status bt-diag-status--%s">%s</span> %s</td></tr>',
                esc_html( $m['release'] ),
                esc_html( $m['file'] ),
                esc_html( $m['desc'] ),
                esc_html( $m['find'] ),
                esc_attr( $status ),
                $status === 'ok' ? 'present' : 'MISSING',
                esc_html( $detail )
            );
        }

        $html  = '<table><thead><tr><th>Release</th><th>File</th><th>What it does</th><th>Marker</th><th>Status</th></tr></thead><tbody>';
        $html .= implode( '', $rows );
        $html .= '</tbody></table>';

        if ( $fail_count === 0 ) {
            return array(
                'status'  => 'ok',
                'summary' => '✓ All ' . count( $markers ) . ' markers present. Files on disk match the v35 ship.',
                'html'    => $html,
                'fail_count' => 0,
            );
        }

        return array(
            'status'  => 'fail',
            'summary' => "✗ {$fail_count} of " . count( $markers ) . " markers MISSING. Source files on disk do NOT match the v32/33/34/35 ships. Likely cause: incomplete plugin upload, or a hosting layer is overlaying old files (e.g. Hostinger AI rewrite, theme overrides in wp-content/mu-plugins).",
            'html'    => $html,
            'fail_count' => $fail_count,
            'missing_files' => $missing_files,
        );
    }

    /* ════════════════════════════════════════════════════════════════════
     *  LAYER 2 — TEMPLATE RESOLUTION
     *  ════════════════════════════════════════════════════════════════════ */

    private static function layer_2_template_resolution() {
        global $wpdb;

        // Check site-takeover state
        $takeover_disabled = (bool) get_option( 'bt_disable_site_takeover', 0 );
        $homepage_revamped = (bool) get_option( 'bt_use_revamped_homepage', 0 );
        $global_nav        = (bool) get_option( 'bt_use_global_nav', 0 );

        // Check what classes are responsible for rendering each page type
        $hooks = array();
        global $wp_filter;
        foreach ( array( 'wp_body_open', 'the_content', 'template_include' ) as $hook_name ) {
            if ( ! isset( $wp_filter[ $hook_name ] ) ) continue;
            foreach ( $wp_filter[ $hook_name ]->callbacks as $priority => $callbacks ) {
                foreach ( $callbacks as $cb ) {
                    $fn = $cb['function'];
                    if ( is_array( $fn ) ) {
                        $name = ( is_object( $fn[0] ) ? get_class( $fn[0] ) : $fn[0] ) . '::' . $fn[1];
                    } elseif ( is_string( $fn ) ) {
                        $name = $fn;
                    } else {
                        $name = 'Closure / unknown';
                    }
                    if ( strpos( $name, 'BT_' ) === 0 || strpos( $name, 'bt_' ) === 0 || strpos( $name, 'fxlm_' ) === 0 ) {
                        $hooks[] = array( 'hook' => $hook_name, 'priority' => $priority, 'callback' => $name );
                    }
                }
            }
        }

        // Active theme
        $theme = wp_get_theme();
        $theme_name = $theme->get( 'Name' ) . ' ' . $theme->get( 'Version' );

        // mu-plugins?
        $mu_plugins = array();
        if ( defined( 'WPMU_PLUGIN_DIR' ) && is_dir( WPMU_PLUGIN_DIR ) ) {
            foreach ( glob( WPMU_PLUGIN_DIR . '/*.php' ) as $p ) {
                $mu_plugins[] = basename( $p );
            }
        }

        // Page-by-page resolution
        $pages_to_check = array(
            '/'                    => 'Homepage',
            '/trading-signals/'    => 'Trading Signals',
            '/analysis/bitcoin/'   => 'Analysis · BTC',
            '/news/breaking/'      => 'News · Breaking',
            '/top-lists/'          => 'Top Lists',
        );
        $page_rows = array();
        foreach ( $pages_to_check as $path => $label ) {
            $page_obj = get_page_by_path( trim( $path, '/' ), OBJECT, 'page' );
            $exists = (bool) $page_obj;
            $status = $page_obj ? $page_obj->post_status : '—';
            $template = $page_obj ? get_post_meta( $page_obj->ID, '_wp_page_template', true ) : '—';
            $page_rows[] = sprintf(
                '<tr><td>%s</td><td><code>%s</code></td><td>%s</td><td><code>%s</code></td><td><code>%s</code></td></tr>',
                esc_html( $label ),
                esc_html( $path ),
                $exists ? '<span class="bt-diag-status bt-diag-status--ok">exists</span>' : '<span class="bt-diag-status bt-diag-status--fail">missing</span>',
                esc_html( $status ),
                esc_html( $template ?: 'default' )
            );
        }

        $html  = '<h3>Site state</h3>';
        $html .= '<table><tr><td>Active theme</td><td><code>' . esc_html( $theme_name ) . '</code></td></tr>';
        $html .= '<tr><td><code>bt_disable_site_takeover</code></td><td><code>' . ( $takeover_disabled ? 'TRUE — TAKEOVER OFF' : 'false (default)' ) . '</code></td></tr>';
        $html .= '<tr><td><code>bt_use_revamped_homepage</code></td><td><code>' . ( $homepage_revamped ? 'true' : 'false (default)' ) . '</code></td></tr>';
        $html .= '<tr><td><code>bt_use_global_nav</code></td><td><code>' . ( $global_nav ? 'true' : 'false' ) . '</code></td></tr>';
        $html .= '<tr><td>mu-plugins</td><td>' . ( $mu_plugins ? '<code>' . esc_html( implode( ', ', $mu_plugins ) ) . '</code>' : '<em>none</em>' ) . '</td></tr>';
        $html .= '</table>';

        $html .= '<h3>Pages</h3>';
        $html .= '<table><thead><tr><th>Label</th><th>Path</th><th>Exists?</th><th>Status</th><th>Template</th></tr></thead><tbody>' . implode( '', $page_rows ) . '</tbody></table>';

        $html .= '<h3>BT/fxlm hooks on render path</h3>';
        if ( $hooks ) {
            $hook_rows = '';
            foreach ( $hooks as $h ) {
                $hook_rows .= sprintf(
                    '<tr><td><code>%s</code></td><td>%d</td><td><code>%s</code></td></tr>',
                    esc_html( $h['hook'] ),
                    intval( $h['priority'] ),
                    esc_html( $h['callback'] )
                );
            }
            $html .= '<table><thead><tr><th>Hook</th><th>Priority</th><th>Callback</th></tr></thead><tbody>' . $hook_rows . '</tbody></table>';
        } else {
            $html .= '<p><em>No BT/fxlm callbacks on render hooks. ⚠ This is suspicious — the takeover should register at least <code>BT_Page_Provisioner::render_global_chrome</code> on <code>wp_body_open</code>.</em></p>';
        }

        $status = 'ok';
        $summary = 'Rendering paths inventoried. Cross-reference against the page that\'s NOT showing audit fixes — if takeover is OFF, that explains everything.';

        if ( $takeover_disabled ) {
            $status = 'fail';
            $summary = '✗ Site takeover is DISABLED. The bt-tokens.css design system + audit fixes only apply when takeover is active. Set bt_disable_site_takeover=0 in wp_options.';
        } elseif ( ! $hooks ) {
            $status = 'fail';
            $summary = '✗ No BT/fxlm callbacks registered on render hooks. The plugin is loaded but its render path is detached. Possible cause: another plugin / theme is calling remove_action() on our hooks.';
        }

        return array(
            'status'  => $status,
            'summary' => $summary,
            'html'    => $html,
        );
    }

    /* ════════════════════════════════════════════════════════════════════
     *  LAYER 3 — CSS LOAD CHECK
     *  ════════════════════════════════════════════════════════════════════ */

    private static function layer_3_css_load() {
        // Check critical CSS files are on disk + contain v33 markers
        $critical = array(
            'bt-tokens.css' => array(
                'path'    => BT_DIR . 'assets/css/bt-tokens.css',
                'markers' => array(
                    '#7B8AA0'                          => 'v32 contrast bump',
                    '§13.1  Crypto table asset cell'   => 'v33 crypto-table grid',
                    '§13.3  Asset-page background cap' => 'v33 asset-page bg',
                    'fxlm-cft-asset__name'             => 'v33 crypto-table classes',
                    'foot__socials a'                  => 'v33 footer touch targets',
                ),
            ),
            'a11y.css' => array(
                'path'    => BT_DIR . 'assets/css/a11y.css',
                'markers' => array(
                    'bt-skip-link'   => 'skip-link CSS',
                    'focus-visible'  => 'focus-ring rules',
                ),
            ),
        );

        $rows = array();
        $any_fail = false;
        foreach ( $critical as $file => $info ) {
            if ( ! file_exists( $info['path'] ) ) {
                $rows[] = sprintf(
                    '<tr><td><code>%s</code></td><td colspan="3"><span class="bt-diag-status bt-diag-status--fail">FILE MISSING</span></td></tr>',
                    esc_html( $file )
                );
                $any_fail = true;
                continue;
            }

            $contents = file_get_contents( $info['path'] );
            $size = filesize( $info['path'] );
            $mtime = filemtime( $info['path'] );

            $rows[] = sprintf(
                '<tr><td><code>%s</code></td><td>%s</td><td colspan="2">mtime <code>%s</code></td></tr>',
                esc_html( $file ),
                size_format( $size ),
                esc_html( gmdate( 'Y-m-d H:i', $mtime ) )
            );

            foreach ( $info['markers'] as $marker => $desc ) {
                $present = ( strpos( $contents, $marker ) !== false );
                if ( ! $present ) $any_fail = true;
                $rows[] = sprintf(
                    '<tr><td></td><td>%s</td><td><code>%s</code></td><td><span class="bt-diag-status bt-diag-status--%s">%s</span></td></tr>',
                    esc_html( $desc ),
                    esc_html( $marker ),
                    $present ? 'ok' : 'fail',
                    $present ? 'present' : 'MISSING'
                );
            }
        }

        $html = '<table><thead><tr><th>File</th><th>What</th><th>Marker</th><th>Status</th></tr></thead><tbody>' . implode( '', $rows ) . '</tbody></table>';

        // Also enumerate enqueued stylesheets at this moment (admin-side context — limited usefulness, but flags WP-side issues)
        global $wp_styles;
        $enqueued_html = '';
        if ( $wp_styles && is_object( $wp_styles ) ) {
            $bt_styles = array();
            foreach ( $wp_styles->registered as $handle => $style ) {
                if ( strpos( $handle, 'bt-' ) === 0 || strpos( $handle, 'fxlm-' ) === 0 || strpos( $handle, 'btlp-' ) === 0 ) {
                    $bt_styles[] = sprintf(
                        '<tr><td><code>%s</code></td><td><code>%s</code></td><td><code>%s</code></td></tr>',
                        esc_html( $handle ),
                        esc_html( str_replace( site_url(), '', $style->src ) ),
                        esc_html( $style->ver ?: '—' )
                    );
                }
            }
            if ( $bt_styles ) {
                $enqueued_html = '<h3>BT-registered stylesheets (this admin request — may differ from public render)</h3>';
                $enqueued_html .= '<table><thead><tr><th>Handle</th><th>URL</th><th>Version</th></tr></thead><tbody>' . implode( '', $bt_styles ) . '</tbody></table>';
            }
        }

        if ( $any_fail ) {
            return array(
                'status'  => 'fail',
                'summary' => '✗ One or more CSS markers missing. The on-disk CSS does not contain the v33 rules. The plugin upload was incomplete OR a build process is overwriting the file.',
                'html'    => $html . $enqueued_html,
            );
        }

        return array(
            'status'  => 'ok',
            'summary' => '✓ All CSS markers present in on-disk files. v33 rules ARE in the source CSS. If they\'re not rendering, the issue is downstream (Layer 4 cascade or Layer 5 markup).',
            'html'    => $html . $enqueued_html,
        );
    }

    /* ════════════════════════════════════════════════════════════════════
     *  LAYER 4 — CASCADE / DEQUEUE CHECK
     *  ════════════════════════════════════════════════════════════════════ */

    private static function layer_4_cascade_check() {
        // Look for plugin/theme code that dequeues bt-tokens or related handles
        $patterns_to_search = array(
            'wp_dequeue_style.*bt-tokens',
            'wp_dequeue_style.*bt-typography',
            'wp_dequeue_style.*bt-a11y',
            'remove_action.*landing.*chrome',
        );

        $hits = array();
        $search_dirs = array(
            WP_PLUGIN_DIR,
            get_template_directory(),
        );
        if ( get_template_directory() !== get_stylesheet_directory() ) {
            $search_dirs[] = get_stylesheet_directory();
        }
        if ( defined( 'WPMU_PLUGIN_DIR' ) && is_dir( WPMU_PLUGIN_DIR ) ) {
            $search_dirs[] = WPMU_PLUGIN_DIR;
        }

        // We don't actually grep the filesystem — too slow for a live request.
        // Instead, audit the known dequeue points in our own code.
        $own_dequeues = array();
        $self_check_files = array(
            BT_DIR . 'includes/class-landing-takeover.php',
            BT_DIR . 'includes/class-asset-pages.php',
            BT_DIR . 'includes/class-page-provisioner.php',
            BT_DIR . 'includes/class-site-takeover.php',
        );
        foreach ( $self_check_files as $file ) {
            if ( ! file_exists( $file ) ) continue;
            $contents = file_get_contents( $file );
            $lines = explode( "\n", $contents );
            foreach ( $lines as $idx => $line ) {
                if ( preg_match( '/wp_dequeue_(style|script)\s*\(\s*[\'"]([a-z0-9_-]+)[\'"]/i', $line, $m ) ) {
                    $own_dequeues[] = array(
                        'file' => str_replace( BT_DIR, '', $file ),
                        'line' => $idx + 1,
                        'kind' => $m[1],
                        'handle' => $m[2],
                        'context' => trim( $line ),
                    );
                }
            }
        }

        $rows = '';
        $bt_self_dequeue = false;
        foreach ( $own_dequeues as $d ) {
            $is_bt = ( strpos( $d['handle'], 'bt-' ) === 0 || strpos( $d['handle'], 'btlp-' ) === 0 );
            if ( $is_bt ) $bt_self_dequeue = true;
            $rows .= sprintf(
                '<tr><td><code>%s:%d</code></td><td>%s</td><td><code>%s</code></td><td>%s</td></tr>',
                esc_html( $d['file'] ),
                $d['line'],
                esc_html( $d['kind'] ),
                esc_html( $d['handle'] ),
                $is_bt ? '<span class="bt-diag-status bt-diag-status--fail">DEQUEUEING OUR OWN STYLE</span>' : '<span class="bt-diag-status bt-diag-status--ok">third-party (OK)</span>'
            );
        }

        $html = '<h3>Dequeue calls in our own code</h3>';
        if ( $own_dequeues ) {
            $html .= '<table><thead><tr><th>Location</th><th>Kind</th><th>Handle</th><th>Verdict</th></tr></thead><tbody>' . $rows . '</tbody></table>';
        } else {
            $html .= '<p>No <code>wp_dequeue_*</code> calls found in plugin source. ✓</p>';
        }

        // Test: bt-tokens.css full URL fetch test (for the public site, not admin)
        $tokens_url = plugins_url( 'assets/css/bt-tokens.css', BT_DIR . 'fx-live-markets.php' ) . '?ver=' . BT_VERSION;
        $html .= '<h3>Direct bt-tokens.css fetch test</h3>';
        $html .= '<p>Manually fetch this URL to confirm CDN/cache state: <a href="' . esc_url( $tokens_url ) . '" target="_blank" rel="noopener"><code>' . esc_html( $tokens_url ) . '</code></a></p>';
        $html .= '<p>Use DevTools → Network → click that file → check the <code>?ver=</code> query string and the response body for <code>§13.1</code>. If <code>?ver=</code> doesn\'t match <code>' . esc_html( BT_VERSION ) . '</code>, the URL is being cached at CDN/edge and you need to purge.</p>';

        if ( $bt_self_dequeue ) {
            return array(
                'status'  => 'fail',
                'summary' => '✗ Plugin code is dequeueing its own stylesheets. This is the bug from Pass 2 §12 — fixing requires removing that dequeue call.',
                'html'    => $html,
            );
        }

        return array(
            'status'  => 'ok',
            'summary' => '✓ No self-dequeue. Cascade should be clean (verify CDN cache via direct URL test below).',
            'html'    => $html,
        );
    }

    /* ════════════════════════════════════════════════════════════════════
     *  LAYER 5 — RENDER OUTPUT CHECK
     *  ════════════════════════════════════════════════════════════════════ */

    private static function layer_5_render_check() {
        // Fetch the live homepage HTML and check for v32/33 markers in actual output
        $home_url = home_url( '/' );
        $resp = wp_remote_get( $home_url, array(
            'timeout'   => 10,
            'sslverify' => false,
            'headers'   => array(
                // Bypass any logged-in cookie — fetch as a fresh anonymous visitor
                'Cookie' => '',
                'User-Agent' => 'BT-Diagnostic/1.0',
            ),
        ));

        if ( is_wp_error( $resp ) ) {
            return array(
                'status'  => 'fail',
                'summary' => '✗ Could not fetch homepage: ' . esc_html( $resp->get_error_message() ),
                'html'    => '<p><em>HTTP fetch failed — cannot verify rendered output.</em></p>',
            );
        }

        $code = wp_remote_retrieve_response_code( $resp );
        $body = wp_remote_retrieve_body( $resp );

        if ( $code !== 200 ) {
            return array(
                'status'  => 'fail',
                'summary' => "✗ Homepage returned HTTP {$code}. Cannot verify rendered output.",
                'html'    => '<p>Body excerpt:</p><pre>' . esc_html( substr( $body, 0, 500 ) ) . '</pre>',
            );
        }

        // Check for v32/33 render markers in actual HTML
        $checks = array(
            array(
                'release' => 'v32',
                'find'    => '/#main-content (v119.28.32)',
                'desc'    => '<main> landmark closing comment',
                'fix'     => 'v32 — landing.php template not rendering',
            ),
            array(
                'release' => 'v32',
                'find'    => '<main id="main-content"',
                'desc'    => '<main> landmark opening tag',
                'fix'     => 'v32 — landing.php template not rendering',
            ),
            array(
                'release' => 'v32',
                'find'    => 'href="' . esc_url( home_url( '/desk-brief/' ) ) . '"',
                'desc'    => 'Hero CTA points to /desk-brief/ (not desk-brief.html)',
                'fix'     => 'v32 — old hero markup cached or template not rendering',
            ),
            array(
                'release' => 'v33',
                'find'    => 'bt-tokens.css?ver=' . BT_VERSION,
                'desc'    => 'bt-tokens.css enqueued with current version',
                'fix'     => 'v33+ — CSS not enqueued or being served stale by CDN',
            ),
        );

        // Anti-marker: things that should NOT appear in v32+ output
        $anti_checks = array(
            array(
                'release' => 'v32',
                'find'    => 'href="desk-brief.html"',
                'desc'    => 'OLD broken hero CTA (should be GONE post-v32)',
            ),
            array(
                'release' => 'v33',
                'find'    => '<strong>Today&#039;s Desk Brief</strong><br>',
                'desc'    => 'OLD mega-menu rich pattern (should be GONE post-v33)',
            ),
        );

        $rows = '';
        $any_marker_fail = false;
        foreach ( $checks as $c ) {
            $present = ( strpos( $body, $c['find'] ) !== false );
            if ( ! $present ) $any_marker_fail = true;
            $rows .= sprintf(
                '<tr><td>%s</td><td>%s</td><td><code>%s</code></td><td><span class="bt-diag-status bt-diag-status--%s">%s</span></td></tr>',
                esc_html( $c['release'] ),
                esc_html( $c['desc'] ),
                esc_html( $c['find'] ),
                $present ? 'ok' : 'fail',
                $present ? 'in output' : 'NOT in output'
            );
        }

        $anti_rows = '';
        $any_anti_fail = false;
        foreach ( $anti_checks as $c ) {
            $present = ( strpos( $body, $c['find'] ) !== false );
            if ( $present ) $any_anti_fail = true;
            $anti_rows .= sprintf(
                '<tr><td>%s</td><td>%s</td><td><code>%s</code></td><td><span class="bt-diag-status bt-diag-status--%s">%s</span></td></tr>',
                esc_html( $c['release'] ),
                esc_html( $c['desc'] ),
                esc_html( $c['find'] ),
                $present ? 'fail' : 'ok',
                $present ? 'STILL IN OUTPUT (regression)' : 'gone (correct)'
            );
        }

        // Length + body class check
        $body_class_match = '';
        if ( preg_match( '/<body([^>]*)>/i', $body, $m ) ) {
            $body_class_match = $m[1];
        }

        $html  = '<h3>Markers expected in homepage HTML</h3>';
        $html .= '<table><thead><tr><th>Release</th><th>Description</th><th>Find</th><th>Status</th></tr></thead><tbody>' . $rows . '</tbody></table>';
        $html .= '<h3>Anti-markers — pre-fix patterns that should be GONE</h3>';
        $html .= '<table><thead><tr><th>Release</th><th>Description</th><th>Should NOT find</th><th>Status</th></tr></thead><tbody>' . $anti_rows . '</tbody></table>';
        $html .= '<h3>Page meta</h3>';
        $html .= '<table>';
        $html .= '<tr><td>Response code</td><td><code>' . intval( $code ) . '</code></td></tr>';
        $html .= '<tr><td>Body length</td><td><code>' . number_format( strlen( $body ) ) . '</code> bytes</td></tr>';
        $html .= '<tr><td>&lt;body&gt; tag</td><td><code>' . esc_html( substr( $body_class_match, 0, 300 ) ) . '</code></td></tr>';
        $html .= '</table>';

        if ( $any_marker_fail || $any_anti_fail ) {
            return array(
                'status'  => 'fail',
                'summary' => '✗ Live HTML output does NOT match v32/33 expected output. The plugin code on disk has the fixes (Layer 1) but the rendered page does not include them. Most likely: a different template is rendering, OR a cache layer (Cloudflare, Hostinger Cache, theme cache) is serving pre-v32 HTML.',
                'html'    => $html,
            );
        }

        return array(
            'status'  => 'ok',
            'summary' => '✓ Live HTML output contains all v32/33 markers. The audit fixes ARE rendering.',
            'html'    => $html,
        );
    }

    /* ════════════════════════════════════════════════════════════════════
     *  FINAL DIAGNOSIS
     *  ════════════════════════════════════════════════════════════════════ */

    private static function render_final_diagnosis( $layers ) {
        $first_fail = null;
        foreach ( $layers as $i => $layer ) {
            if ( $layer['status'] === 'fail' ) { $first_fail = $i + 1; break; }
        }

        if ( $first_fail === null ) {
            echo '<div class="layer-summary layer-summary--ok"><strong>All five layers green.</strong> The audit fixes are physically on disk, served, and rendering. If you\'re still not SEEING them, the issue is purely visual perception — try comparing screenshots of the same pages side-by-side from before v32 vs. now.</div>';
            return;
        }

        $diagnoses = array(
            1 => '<strong>The plugin upload is incomplete or being overwritten.</strong> Source files on disk don\'t contain v32/33/34 markers. ACTION: SSH/SFTP into the site, check <code>wp-content/plugins/blockticker-io/</code> file modification times. Re-upload the v35 ZIP via SFTP (not WP Admin upload — bypasses any auto-install hooks).',

            2 => '<strong>Site takeover or template routing is broken.</strong> Plugin code is on disk but the rendering pipeline isn\'t using it. ACTION: in WP Admin → BlockTicker → Page Manager, confirm "Use revamped homepage" is ON. If Hostinger is overlaying anything, check <code>/wp-content/mu-plugins/</code> for surprise files.',

            3 => '<strong>CSS file is on disk but missing v33 rules.</strong> ACTION: open <code>wp-content/plugins/blockticker-io/assets/css/bt-tokens.css</code> directly via SFTP and grep for "§13.1" — if it\'s not there, the file was overwritten by an older version.',

            4 => '<strong>Cascade conflict — something is dequeueing our CSS or overriding our selectors.</strong> ACTION: temporarily deactivate every other plugin and switch to a default theme (Twenty Twenty-Four). Re-test. If audit fixes appear, a third-party plugin/theme is the culprit.',

            5 => '<strong>Code on disk is correct, but rendered HTML doesn\'t match.</strong> This is almost always CDN/page-cache. ACTION: (1) Hostinger Site Tools → Caching → Purge all. (2) Cloudflare (if used) → Caching → Purge Everything. (3) Test in incognito mode immediately after. (4) If still wrong, deactivate any caching plugins (WP Rocket, W3 Total Cache, LiteSpeed Cache) and re-test.',
        );

        $action = $diagnoses[ $first_fail ] ?? 'Unknown — see layer details above.';

        echo '<div class="layer-summary layer-summary--fail"><strong>First failure: Layer ' . intval( $first_fail ) . '.</strong> ' . $action . '</div>';

        // Copy-to-clipboard report summary
        $summary_lines = array();
        $summary_lines[] = '=== BlockTicker Diagnostic — ' . gmdate( 'Y-m-d H:i' ) . ' UTC ===';
        $summary_lines[] = 'Plugin version: ' . BT_VERSION;
        $summary_lines[] = 'WP version: ' . get_bloginfo( 'version' );
        $summary_lines[] = '';
        foreach ( $layers as $i => $l ) {
            $summary_lines[] = sprintf( 'Layer %d — %s', $i + 1, strtoupper( $l['status'] ) );
            $summary_lines[] = '  ' . $l['summary'];
            $summary_lines[] = '';
        }
        $summary_lines[] = 'First-failing layer: ' . ( $first_fail ?: 'none' );

        echo '<h3>Copy-paste summary (send this to engineering)</h3>';
        echo '<div class="copy-section">' . esc_html( implode( "\n", $summary_lines ) ) . '</div>';
    }
}
